version: '3.0'
services:
  api:
    build: .
    volumes:
     - ./:/app
    ports:
     - "9999:9999"
    environment:
      PGPASSWORD: test
    tty: true
    depends_on: 
     - db
  
  db:
    image: postgres:11
    ports:
     - "5432:5432"
    environment: 
      TZ: Asia/Tokyo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sample_db_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
     - ./build/containers/postgresql:/docker-entrypoint-initdb.d
    tty: true
